name: Deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job'
        required: true
        default: 'build'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: npm install package
      run: npm install
    - name: build
      env:
        CI: false
      run: npm run build
