name: Deploy

on:
  push:
    branches: [ "master" ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: npm install package
      run: npm install
    - name: build
      env:
        CI: false
      run: npm run build
